### ISSUE TITLE
NoSuchMethodError in LGBMDataset.createFromMat on Win (Java)

### ISSUE THREAD

**Issue by jornd13** [metarank/lightgbm4j#70]
I'm trying to run the Java lightgbm4j wrapper on Windows and I cannot get around the following error, no matter which library versions etc. I use. The call is embedded in proprietary code (see below). I rely on the Maven version of LGBM4J:

<dependency>
    <groupId>io.github.metarank</groupId>
    <artifactId>lightgbm4j</artifactId>
    <version>3.3.2-5</version>
</dependency>

Switching to the float variant of the method does not help either.

When I try different (lower) lib versions from Maven I end up with UnsatisfiedLinkError (see at the bottom).

Stack trace for use of lightgbm4j 3.3.2-5:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/H:/m2/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/H:/m2/org/slf4j/slf4j-log4j12/1.7.26/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "Thread-7" java.lang.NoSuchMethodError: com.microsoft.ml.lightgbm.lightgbmlib.new_doubleArray(J)Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_double;
	at io.github.metarank.lightgbm4j.LGBMDataset.createFromMat(LGBMDataset.java:93)
	at weka.classifiers.functions.LGBMClassifier.buildClassifier(LGBMClassifier.java:78)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:2049)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:1679)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.generateClassifierGeneric(WekaClassifierAdapter.java:2317)
	at control.MFNController.trainWekaClassifier(MFNController.java:5392)
	at control.MFNController.generatePQReportWekaClassifier(MFNController.java:4562)
	at control.ParameterSpaceExplorationAgent.run(ParameterSpaceExplorationAgent.java:1847)

______________________________________________________
Stack trace for use of lower versions of lightgbm4j:

Exception in thread "Thread-7" java.lang.UnsatisfiedLinkError: com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()J
	at com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp(Native Method)
	at com.microsoft.ml.lightgbm.lightgbmlib.new_voidpp(lightgbmlib.java:489)
	at io.github.metarank.lightgbm4j.LGBMDataset.createFromMat(LGBMDataset.java:51)
	at weka.classifiers.functions.LGBMClassifier.buildClassifier(LGBMClassifier.java:78)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:2049)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:1679)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.generateClassifierGeneric(WekaClassifierAdapter.java:2317)
	at control.MFNController.trainWekaClassifier(MFNController.java:5392)

**Comment by jornd13** [comment]
Thanks a lot. Yes, a Maven-based build. mmlspark it's commented out in the Maven POM, which I also attached.
[pom.xml.txt](https://github.com/metarank/lightgbm4j/files/13493361/pom.xml.txt)

Might it be some sort of clean-up / clean-build issue?

When I print out the cp straight from the running application (System.getProperty("java.class.path")), I don't see any version of mmlspark on it. Not sure how to get to the bottom of this...?

**Comment by jornd13** [comment]
Are you very certain that only the mmlspark lib has the LGBM lib wrapped out of the items in the pom? Any other suggestions to debug this further? What's a bit weird is that I obtain an UnsatisfiedLinkError when downgrading the LGBM version.
Thanks a lot.

**Comment by shuttie** [comment]
@jornd13 I've added a check for native library mismatch while loading it (and also a couple of hacks to make it not conflict with mmlspark), so you should try the new 4.1 release. If the error persists - please reopen the ticket.

**Comment by shuttie** [comment]
Can you show a full log on the error message? Your original message mentions that logging is not configured and there's only a stack trace. As an example, add the logback-classic to the dependency list.

**Comment by jornd13** [comment]
Is this info useful or do you need more (if so, how to have that logged)? Thanks a lot.

**Comment by jornd13** [comment]
Would love to re-open this, since it's not solved from my perspective.
