### ISSUE TITLE
NoSuchMethodError in LGBMDataset.createFromMat on Win (Java)

### ISSUE THREAD

**Issue by jornd13** [metarank/lightgbm4j#78]
Despit #73 I'm still getting the following error - there are some print-outs from LGBMBooster:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/H:/m2/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/H:/m2/org/slf4j/slf4j-log4j12/1.7.26/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
i.g.m.l.LGBMBooster - Loading native lib from resource lightgbm4j/windows/x86_64//lib_lightgbm.dll
i.g.m.l.LGBMBooster - C:\Users*\AppData\Local\Temp\lib_lightgbm.dll already exists
i.g.m.l.LGBMBooster - Extracted file: exists=true path=C:\Users*\AppData\Local\Temp\lib_lightgbm.dll
i.g.m.l.LGBMBooster - Loading native lib from resource lightgbm4j/windows/x86_64//lib_lightgbm_swig.dll
i.g.m.l.LGBMBooster - C:\Users*\AppData\Local\Temp\lib_lightgbm_swig.dll already exists
i.g.m.l.LGBMBooster - Extracted file: exists=true path=C:\Users*\AppData\Local\Temp\lib_lightgbm_swig.dll
Exception in thread "Thread-7" java.lang.NoSuchMethodError: com.microsoft.ml.lightgbm.lightgbmlib.new_doubleArray(J)Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_double;
at io.github.metarank.lightgbm4j.LGBMDataset.createFromMat(LGBMDataset.java:93)
at weka.classifiers.functions.LGBMClassifier.buildClassifier(LGBMClassifier.java:79)
at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:2050)
at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:1680)
at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.generateClassifierGeneric(WekaClassifierAdapter.java:2318)
at control.MFNController.trainWekaClassifier(MFNController.java:5397)
at control.MFNController.generatePQReportWekaClassifier(MFNController.java:4567)
at control.ParameterSpaceExplorationAgent.run(ParameterSpaceExplorationAgent.java:1847)

Can you conclude anything from the dll-related infos? Does it mean there is an artifact file lib_lightgbm.dll which is not actually the one that should be used / does not get overwritten with the actual one from metarank?

Is this info useful or do you need more (if so, how to have that logged)? Thanks a lot.

**Comment by jornd13** [comment]
I am one step further, I overcame the issue above by hunting down the faulty outdated code that overshadowed the metarank lib. 
Essentially I had redundant and outdated Java classes for com.microsoft.ml.lightgbm (not another conflicting library) in my project path that weren't showing in the IDE.

Now I am running into a new issue - the application crashing outside the JVM at inference time, for which I will create a separate tracking issue here.
